src/gpu/vulkan/SDL_gpu_vulkan.c

It should now be clearer which memory types are being chosen for specific purposes. Transfer buffers now request VK_MEMORY_PROPERTY_HOST_CACHED_BIT which should speed things up too.
Fixes: https://github.com/thatcosmonaut/SDL/issues/15

Vulkan: Buffer memory type refinement

---

include/SDL3/SDL_gpu.h
src/dynapi/SDL_dynapi_procs.h
src/gpu/SDL_gpu.c
src/gpu/SDL_gpu_driver.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c
test/testgpu_spinning_cube.c

Found a workaround for D3D11, so these types are no longer needed.

Transfer usage restructuring and D3D11 async readback

---

include/SDL3/SDL_gpu.h
src/gpu/SDL_gpu.c
src/gpu/SDL_gpu_driver.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c

This should clarify the usage of the parameters in the Upload/Download functions.

Rename transfer parameters to source and destination

---

include/SDL3/SDL_gpu.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c

For the next batch of ABI breaks.
D3D11 and Metal don't support depth bounds tests at all, and Vulkan only supports them if the `depthBounds` feature is enabled (which we weren't using).

Remove depth bounds test

---

include/SDL3/SDL_gpu.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c

Vulkan requires that the border color of a sampler match the format (int vs. float) of the texture it will be used with. This is an annoying limitation for an already-niche feature, so let's just cut the feature entirely.

Remove support for border colors

---

include/SDL3/SDL_gpu.h

Closes https://github.com/thatcosmonaut/SDL/issues/57. Added documentation about how swapchain parameters should be queried before calling ClaimWindow or SetSwapchainParameters. Though I am wondering if the latter should return an SDL_bool indicating whether it succeeded or not...

Swapchain parameter documentation

---

include/SDL3/SDL_gpu.h
src/dynapi/SDL_dynapi_procs.h
src/gpu/SDL_gpu.c
src/gpu/SDL_gpu_driver.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c

Should be merged alongside #60

SetSwapchainParameters and PrepareDriver return SDL_bool

---

include/SDL3/SDL_gpu.h

Fixes https://github.com/thatcosmonaut/SDL/issues/64. Added documentation for how to author resource bindings in the various shader backends.

Document resource binding order

---

src/gpu/SDL_gpu.c

This check was causing almost all of the SDL_gpu_examples to fail.

depthStencilAttachmentInfo is allowed to be null

---

src/gpu/metal/SDL_gpu_metal.m

Forgot to update this during the last round of uniform changes. This fixes a crash in testgpu_spinning_cube.

metal: Push*UniformData should not rely on a bound pipeline

---

src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c
test/testgpu_spinning_cube.c

Implemented MSAA for color and depth-stencil buffers, added support for 2D array textures and cube textures, cleaned up a bunch of FIXMEs, and added a warning check for Vulkan to ensure blitting works consistently across backends. I also added an `--msaa` option for testgpu_spinning_cube to see MSAA in practice.

metal: Improved texture type support

---

src/gpu/vulkan/SDL_gpu_vulkan.c

Adds feature checks and fallback logic for `fillModeNonSolid` which is only supported on ~50% of Android devices and `multiDrawIndirect` which has ~67% support on Android.

vulkan: Add device feature queries

---

src/gpu/vulkan/SDL_gpu_vulkan.c

Changed Vulkan memory binding to not have to get the filter types repeatedly. Broke down memory properties into required, preferred, and tolerable. Additionally, transfer buffers now require coherent memory.

improved vulkan memory type iteration

---

src/gpu/d3d11/SDL_gpu_d3d11.c

When compiling an hlsl shader on D3D11 currently the entryPointName is being ignored.
Switched from the hardcoded "main" to using what was passed in to the function already from the user.

Don't ignore entryPointName in d3d11 backend.

---

src/gpu/d3d12/SDL_gpu_d3d12.c

Partial construction of these values can occur when initialization fails half way through, so cleanup in a way that is robust with NULL checks

Be more paranoid about the cleanup in D3D12_INTERNAL_DestroyRenderer

---

include/SDL3/SDL_gpu.h
src/gpu/SDL_gpu.c
src/gpu/SDL_sysgpu.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c

Adjust to match
https://github.com/thatcosmonaut/SDL/issues/135
-- this is for after
https://github.com/thatcosmonaut/SDL/pull/132

Change primitiveCount to vertexCount

---

include/SDL3/SDL_gpu.h
src/gpu/SDL_gpu.c
src/gpu/SDL_sysgpu.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c

Setting up texture creation validation. This has the prerequisite of moving all texture metadata info to the container in a common header (https://github.com/thatcosmonaut/SDL/issues/95) so I'm working on that incrementally.

Texture Validation

---

src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m

Pretty self-explanatory. This fixes the Blit regression on D3D11, D3D12, and Metal.

Update Blit implementations to use vertexCount

---

include/SDL3/SDL_gpu.h
src/dynapi/SDL_dynapi.sym
src/dynapi/SDL_dynapi_overrides.h
src/dynapi/SDL_dynapi_procs.h
src/gpu/SDL_gpu.c
src/gpu/SDL_sysgpu.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c
test/testgpu_spinning_cube.c

Removing these in favor of Map/Unmap. Incidentally this also lets us remove the SDL_GpuTransferBufferRegion struct since it was used exclusively for these functions.

Remove SetTransferData/GetTransferData APIs

---

src/gpu/d3d12/SDL_gpu_d3d12.c

None of the necessary functions are supported by D3D12:
https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setmarker
https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-beginevent
So we just emit an info log and bail.

D3D12: Renderdoc debug markers

---

src/gpu/SDL_gpu.c
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c

Merge #175 before this one. Resolves #117 and #134. 
You no longer have to bind a pipeline before binding graphics or compute resources. 
Bound graphics state is now explicitly unset on EndRenderPass and EndComputePass. Note that uniform buffers are an exception because those are managed internally and not bound by the client.

Relax bind order requirement and unset bound state on pass end

---

include/SDL3/SDL_gpu.h

Realized we hadn't updated the docs for resource binding order since adding D3D12.

Update docs for DXBC SM5/5.1 shaders

---

src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c

Closes #187.
Marking as draft because D3D12 is unhappy with this change. Seems like there's maybe a state transition missing somewhere? All the examples have the validation error: 
`D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x000001856F440690:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x7E2FEB70: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x000001856F4377A0:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x7E2FEB50: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x7E2FEB30: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]`

Change swapchains to be write-only

---

src/gpu/SDL_gpu.c

Make it clear when unsupported shader formats cause a device creation failure if user asked for a specific backend.
The existing "SDL_HINT_GPU_BACKEND X unsupported!" error can be confusing in this situation as seen in issue #181 discussion.

Log shader format mismatch when asking for a specific backend

---

src/gpu/SDL_gpu.c

Currently, SDL will choose the default driver if no driver name is passed to ``SDL_GpuCreateDevice()``, even if it doesn't support the listed shader formats. This then invariably results in the device being useless, and the program either noticing this and quitting, or eventually hitting an "Incompatible shader format for GPU backend" assertion.
Instead, let's just remove any incompatible devices from the list. This does require users to actually provide the correct list of supported shader formats properly, lest they don't get a device, but that's probably a good thing.
As of #199, we do a similar check (and log an error) if a specific driver has been requested, but the shader formats don't match. This is basically just extending that to the default selection (without the log message). …

[GPU] Only select drivers with supported shader formats

---

include/SDL3/SDL_gpu.h
src/gpu/SDL_gpu.c
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c
test/testgpu_spinning_cube.c

Layer count and depth are mutually exclusive. For 3D textures layer count has to be 1, and for everything else depth has to be 1, so this revision merges them into one field.
Resolves #67

Consolidate layerCount and depth

---

include/SDL3/SDL_gpu.h
src/dynapi/SDL_dynapi_procs.h
src/gpu/SDL_gpu.c
src/gpu/SDL_sysgpu.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c
test/testgpu_spinning_cube.c

Resolves https://github.com/thatcosmonaut/SDL/issues/206. Reusing SDL_render's `SDL_FlipMode` enum here to avoid reinventing the wheel.

Add BlitRegion struct, add flipMode support

---

include/SDL3/SDL_gpu.h
src/dynapi/SDL_dynapi_procs.h
src/gpu/SDL_gpu.c
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c

- Moved GenerateMipmaps out of the copy pass to the command buffer, like Blit. D3D12 needs to blit in the implementation and Metal needs it to be in a copy pass, so it just shouldn't be inside a pass.
- Implemented D3D12 GenerateMipmaps
- Fixed D3D11 GenerateMipmaps
- Fixed Vulkan GenerateMipmaps not taking depth into account
- Fixed BlitCommon not taking mip level into account in the source dimension calculation
- Moved mip level validation on GenerateMipmaps into SDL_gpu.c 
This will probably conflict with #207 because it depends on Blit, so let's merge that one first and go from there.

GenerateMipmaps

---

src/gpu/vulkan/SDL_gpu_vulkan.c

Resolves #222 
Framebuffers were getting double free'd, also I wasn't checking depth views on framebuffers.

Vulkan: fix framebuffer release logic

---

include/SDL3/SDL_gpu.h
src/dynapi/SDL_dynapi.sym
src/dynapi/SDL_dynapi_overrides.h
src/dynapi/SDL_dynapi_procs.h
src/gpu/SDL_gpu.c
src/gpu/SDL_sysgpu.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c
test/testgpu_spinning_cube.c

Resolves #218 
Removes `SDL_GpuGetBestSampleCount` in favor of a hard query: `SDL_GpuSupportsSampleCount`.

SDL_GpuSupportsSampleCount

---

include/SDL3/SDL_gpu.h
src/dynapi/SDL_dynapi_procs.h
src/gpu/SDL_gpu.c
src/gpu/SDL_sysgpu.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c
test/testgpu_spinning_cube.c

Partially fixes https://github.com/thatcosmonaut/SDL/issues/231

gpu: Add instanceCount parameter to SDL_GpuDrawPrimitives()

---

src/gpu/SDL_gpu.c
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/vulkan/SDL_gpu_vulkan.c

It makes no sense to cycle and load in a render pass, and if the client asks to do this it indicates a fundamental misunderstanding, so we should assert when this happens.

Assert in BeginRenderPass if cycle is true and load op is LOAD

---

include/SDL3/SDL_gpu.h
src/dynapi/SDL_dynapi_procs.h
src/gpu/SDL_gpu.c
src/gpu/SDL_sysgpu.h
src/gpu/d3d11/SDL_gpu_d3d11.c
src/gpu/d3d12/SDL_gpu_d3d12.c
src/gpu/metal/SDL_gpu_metal.m
src/gpu/vulkan/SDL_gpu_vulkan.c

This parameter is signed on all the underlying APIs.

Change vertexOffset to signed
