- src/gpu/d3d11/SDL_gpu_d3d11.c
SDL_GPU_COLORSPACE_LINEAR_SRGB would cause the swapchain to fail to create on flip-model swapchains. This patch addresses that issue by creating the swapchain (for both linear and non-linear) as DXGI_FORMAT_B8G8R8A8_UNORM then setting the render target view's format to DXGI_FORMAT_B8G8R8A8_UNORM_SRGB if the colorspace is  SDL_GPU_COLORSPACE_LINEAR_SRGB
No existing issue is  open for this
> D3D11: Fix SDL_GPU_COLORSPACE_LINEAR_SRGB

- src/gpu/vulkan/SDL_gpu_vulkan.c
Always check return value of `VULKAN_INTERNAL_QuerySwapchainSupport()`, if 1st call to `vkGetPhysicalDeviceSurfacePresentModesKHR()` fails then `outputDetails->formatsLength` is not 0 but `outputDetails->formats` is still not initialised.
Always free `outputDetails->formats` on error in `VULKAN_INTERNAL_QuerySwapchainSupport()`.
Use correct type for allocation of `commandBuffer->presentDatas`.
Do some allocations later to avoid memory leaks on error.
None
> Some fixes for memory handling in Vulkan implementation

- src/gpu/vulkan/SDL_gpu_vulkan.c
> Vulkan: optionally load colorspace extension

- src/gpu/SDL_gpu.c
> prefer Metal backend when available

- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
> Track UBOs on acquisition from pool

- src/gpu/vulkan/SDL_gpu_vulkan.c
We technically already sorta-kinda did this in CreateSwapchain, but not in SupportsSwapchainComposition. This brings the functionality to both functions in a cleaner way.
Was also able to remove some duplication around failure handling in CreateSwapchain, and unified the swapchain/present mode checks to use the VULKAN_INTERNAL_Verify* functions instead of raw loops.
> vulkan: Allow falling back to RGBA surface formats

- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
> Check texture usage flags in BeginComputePass

- src/gpu/vulkan/SDL_gpu_vulkan.c
> Vulkan: Force swapchain recreation if window size changes

- src/gpu/d3d12/SDL_gpu_d3d12.c
Hand pick changes from other branch.
> Hand pick changes from other branch.

- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/vulkan/SDL_gpu_vulkan.c
Aggressively zero-init using NULL/{0}/SDL_zeroa/SDL_calloc
we don't have valgrind to check dx12, so lets be careful
> Aggressively zero-init using NULL/{0}/SDL_zeroa/SDL_calloc

- src/gpu/SDL_sysgpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
This is a prerequisite for compiling D3D12 for Xbox GDK.
> D3D12 C++ compile fixes

- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
Lots of wonderful kludges in this one! 
With this the D3D12 renderer is mostly feature complete - still needs some fixes but the majority of the design work is done.
> D3D12 Copy Pass

- include/SDL3/SDL_gpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
https://github.com/thatcosmonaut/SDL/issues/146
> Limit api to 8bit stencils, which is a dx11 and dx12 limit

- include/SDL3/SDL_gpu.h
- src/dynapi/SDL_dynapi_procs.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- test/testgpu_spinning_cube.c
> MapTransferBuffer should return the mapped pointer

- src/gpu/d3d11/SDL_gpu_d3d11.c
> D3D11: fix texture upload stride calculation

- src/gpu/d3d12/SDL_gpu_d3d12.c
> D3D12 texture upload over-read fix

- src/gpu/vulkan/SDL_gpu_vulkan.c
> Vulkan: fix swapchain image count being too low on some devices

- src/gpu/vulkan/SDL_gpu_vulkan.c
> Replace Vulkan hashtables with SDL_HashTable

- src/gpu/d3d12/SDL_gpu_d3d12.c
> D3D12: handle indirect buffer stride not matching struct size

- include/SDL3/SDL_gpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- test/testgpu_spinning_cube.c
Also actually implements the step rate on the Metal backend.
> Rename stepRate to instanceStepRate

- src/gpu/d3d12/SDL_gpu_d3d12.c
> D3D12: Increment fence refcount on AcquireFence

- include/SDL3/SDL_gpu.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
Rearranging the draw call parameters to bring them in line with the indirect command structures.
> Rearrange draw call parameters

- src/gpu/SDL_gpu.c
We now assert if the client attempts to acquire a swapchain texture during a pass. Also clarifies the assert messages related to passes.
> Clearer pass-related asserts
